apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: gpu
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
  role: eks-worker-node-role  
  securityGroupSelectorTerms:
  - tags:
      kubernetes.io/cluster/llm-deploy-eks: owned
  subnetSelectorTerms:
  - tags:
      kubernetes.io/cluster/llm-deploy-eks: owned