apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: ollama
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
    expireAfter: 720h0m0s
  limits:
    cpu: 1k
    memory: 1000Gi
    nvidia.com/gpu: 10
  template:
    metadata:
      labels:
        nvidia.com/gpu: "true"
    spec:
      nodeClassRef:
        name: gpu
      requirements:
      - key: node.kubernetes.io/instance-type
        operator: In
        values: ["g4dn.xlarge", "g4dn.2xlarge", "g4dn.4xlarge"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
      - key: kubernetes.io/os
        operator: In
        values: ["linux"]
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64"]
      taints:
      - effect: NoSchedule
        key: nvidia.com/gpu
        value: "true"