apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ollama
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: ollama
        image: ollama/ollama:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
        resources:
          limits:
            nvidia.com/gpu: "1"
            cpu: "3600m"
            memory: "4Gi"
          requests:
            nvidia.com/gpu: "1"
            cpu: "3600m"
            memory: "4Gi"
      - name: load-model
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
        - "sleep infinity"
        lifecycle:
          postStart:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - "curl -X POST http://localhost:11434/api/pull -H 'Content-Type: application/json' -d '{\"name\": \"llama3.2\"}'"
        resources:
          limits:
            cpu: "25m"
            memory: "50Mi"

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: openweb-ui
#   name: openweb-ui
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: openweb-ui
#   template:
#     metadata:
#       labels:
#         app: openweb-ui
#     spec:
#       volumes:
#       - name: webui-data
#         persistentVolumeClaim:
#           claimName: ollama-pvc
#       containers:
#       - name: openweb-ui
#         image: ghcr.io/open-webui/open-webui
#         ports:
#         - containerPort: 8080
#         env:
#         - name: OLLAMA_BASE_URL
#           value: "http://svc-ollama:11434"
#         volumeMounts:
#         - name: webui-data
#           mountPath: /app/backend/data
#         resources:
#           requests:
#             cpu: "1000m"
#             memory: "128Mi"
#           limits: 
#             cpu: "2000m"
#             memory: "1Gi"